SELECT * FROM dbo.Feminicidio_exemplo


SELECT COR_PELE, COUNT(COR_PELE) 
FROM dbo.Feminicidio_exemplo
GROUP BY COR_PELE
ORDER BY COUNT(COR_PELE) DESC

SELECT  COR_PELE, COUNT(COR_PELE)FROM dbo.Feminicidio_exemplo
WHERE COR_PELE <> 'BRANCA' AND COR_PELE <> 'PRETA' AND COR_PELE <> 'PARDA'
GROUP BY COR_PELE

SELECT DATAHORA_REGISTRO_BO, COUNT(DATAHORA_REGISTRO_BO) FROM dbo.Feminicidio_exemplo
GROUP BY DATAHORA_REGISTRO_BO
ORDER BY COUNT(DATAHORA_REGISTRO_BO) DESC

SELECT PROFISSAO, COUNT(PROFISSAO) AS 'TOTAL POR PROFISSAO' FROM dbo.Feminicidio_exemplo
WHERE PROFISSAO IS NOT NULL
GROUP BY PROFISSAO
ORDER BY COUNT(PROFISSAO) DESC

SELECT MUNICIPIO_CIRCUNSCRICAO, COUNT(MUNICIPIO_CIRCUNSCRICAO) FROM dbo.Feminicidio_exemplo
WHERE MUNICIPIO_CIRCUNSCRICAO IS NOT NULL
GROUP BY MUNICIPIO_CIRCUNSCRICAO
ORDER BY COUNT(MUNICIPIO_CIRCUNSCRICAO) DESC

SELECT DATA_NASCIMENTO_PESSOA FROM dbo.Feminicidio_exemplo
WHERE DATA_NASCIMENTO_PESSOA IS NOT NULL
ORDER BY DATA_NASCIMENTO_PESSOA ASC


SELECT DATA_FATO, COUNT(DATA_FATO) FROM dbo.Feminicidio_exemplo
GROUP BY DATA_FATO
ORDER BY COUNT(DATA_FATO) DESC

SELECT DESC_TIPOLOCAL, COUNT(DESC_TIPOLOCAL) AS 'TOTAL DE CASOS EM CADA LOCAL' FROM dbo.Feminicidio_exemplo
GROUP BY DESC_TIPOLOCAL
ORDER BY COUNT(DESC_TIPOLOCAL) DESC

SELECT MAX(DATAHORA_REGISTRO_BO) AS 'REGISTRO MAIS ATUAL' FROM dbo.Feminicidio_exemplo

SELECT MIN(DATAHORA_REGISTRO_BO) AS 'REGISTRO MAIS ANTIGO' FROM dbo.Feminicidio_exemplo


SELECT MUNICIPIO_CIRCUNSCRICAO, DEPARTAMENTO_CIRCUNSCRICAO,DATA_FATO FROM dbo.Feminicidio_exemplo

SELECT AVG(IDADE_PESSOA) AS 'MEDIA TOTAL DE IDADE' FROM dbo.Feminicidio_exemplo

SELECT MUNICIPIO_CIRCUNSCRICAO, AVG(IDADE_PESSOA) AS 'MEDIA DE IDADE POR MUNICIPIO ' FROM dbo.Feminicidio_exemplo
GROUP BY MUNICIPIO_CIRCUNSCRICAO

SELECT MUNICIPIO_CIRCUNSCRICAO, COUNT(MUNICIPIO_CIRCUNSCRICAO) FROM dbo.Feminicidio_exemplo
GROUP BY MUNICIPIO_CIRCUNSCRICAO
ORDER BY COUNT(MUNICIPIO_CIRCUNSCRICAO) DESC

SELECT COR_PELE, AVG(IDADE_PESSOA) AS 'MEDIA DE IDADE POR COR DA PELE' FROM dbo.Feminicidio_exemplo
GROUP BY COR_PELE
ORDER BY AVG(IDADE_PESSOA) ASC